seed: 42
id: vgga_lr_1e_3

data:
  data_dir: ./data
  batch_size: 512
  num_workers: 8
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2470, 0.2435, 0.2616]

model:
  name: vgg_a
  use_batchnorm: false
  dropout: 0.0

train:
  epochs: 100
  optimizer: adam
  lr: 0.001
  weight_decay: 0.0
  scheduler: none
  use_amp: true
